### ISSUE TITLE
Bug - Code sample render different quotation mark on IE & Edge

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui-dev#105]
**Describe the bug**<br/>
On IE & Edge, code sample component render different quotation marks, so it breaks the highlighting

**To Reproduce**<br/>
1. Go to component example
2. Click on code example
3. Compare code sample display in Chrome and IE, Edge

**Expected behavior**<br/>
Single quotation mark should be rendered as double

**Desktop (please complete the following information):**<br/>
 - OS: Windows
 - Browser [IE 11, Edge 16]

Related issue #89 
Related PR #104

**Comment by helloimela** [comment]
Chrome:

![image](https://user-images.githubusercontent.com/1199101/63324988-87be9380-c329-11e9-97be-af1c3f168e2a.png)

IE :

![image](https://user-images.githubusercontent.com/1199101/63325028-9ad16380-c329-11e9-8421-13ab93b705d4.png)

**Comment by helloimela** [comment]
This is a low priority issue, we will wait to work on this unless it causes a problem for the user when they copy code from IE.

**Comment by mmexvr** [comment]
In current setup we don't support data rendering at this time.
