### ISSUE TITLE
CDN version of Alpha does not work

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui-dev#106]
https://scania.github.io/corporate-ui-labs/prototypes/misc/faq/faq.html

When runned from GitHub Pages:
![image](https://user-images.githubusercontent.com/10209902/56795379-ae077300-6810-11e9-914a-de8886650c2c.png)

When runned from filesystem:
![image](https://user-images.githubusercontent.com/10209902/56795315-87e1d300-6810-11e9-8cdf-66a9de0ebd91.png)

/Jesper

**Comment by mmexvr** [comment]
#108

**Comment by mmexvr** [comment]
Found the source of the issue and added a new issue for it
