### ISSUE TITLE
Bug - "HTML not parsed in text prop of Footer component"

### ISSUE THREAD

**Issue by quaspar** [scania/corporate-ui-dev#107]
**Describe the bug**<br/>
The Footer component has a prop named "text", which defaults to `Copyright &copy; Scania 2019`. But the `&copy;` is not rendered to a "©". This is because JSX does not parse dynamically inserted html strings, for security reasons. Instead, the attribute dangerouslySetInnerHTML must be used (however, Typescript does not recognize that attribute, so this does not work out of the box, either).

**To Reproduce**<br/>
1. npm start
2. Go to components/Footer in the storybook.
4. See that the copyright text is not parsed correctly, at least where the default text has been leaved untouched.

**Expected behavior**<br/>
The default string should be rendered as "'Copyright © Scania 2019'"

**Additional context**<br/>
It seams an easy fix would look like this: 
`<p data-test-id='c-footer-copyright' dangerouslySetInnerHTML={{"__html": this.text}}>`...

However, Typescript would complain about this, so the type definition of HTMLAttributes would have to be extended somehow. 

Unfortunately, I don't know how to do this.

**Comment by mmexvr** [comment]
Fixed in #119 

We have added the correct copyright symbol
