### ISSUE TITLE
Add data-env like Corporate-UI 3.x

### ISSUE THREAD

**Issue by corte** [scania/corporate-ui-dev#164]
**Is your feature request related to a problem? Please describe.**
Not sure if this should be part of #115, but in corporate ui 3.x we had the attribute data-env on body in order to show in which environment the application is running

**Describe the solution you'd like**
Just like adding a theme we could set the environment as well:
```
import { defineCustomElements, addTheme, **setEnvironment** } from 'corporate-ui-dev';
import { theme as scania } from 'scania-theme'; 

defineCustomElements(['c-theme', 'c-footer', 'c-content']);
addTheme(scania);
setEnvironment('dev');
// or
// setEnvironment(Environments.Development);
```

**Describe alternatives you've considered**
...

**Additional context**
![image](https://user-images.githubusercontent.com/4606160/60948638-ad508a00-a2f3-11e9-96e6-7495438fde69.png)

**Comment by helloimela** [comment]
Please check #204 for the proposed solution

**Comment by mmexvr** [comment]
This has been merged now in scania-theme https://github.com/scania/scania-theme/pull/54
