### ISSUE TITLE
Bug - navigation angular bootstrap drop-down hidden on small screen

### ISSUE THREAD

**Issue by astefan92** [scania/corporate-ui-dev#166]
The navigation drop-down from angular bootstrap goes under c-content instead of being over it on smaller or mobile screens rendering it unusable. 

1. Go to corporate ui angular example app
2. Make the window smaller until the hamburger menu appears (or just use developer tools to set a mobile screen resolution)
3. Open up the USER drop-down
4. Drop-down body is under c-content

**Expected behavior**
The drop-down shows over main content.

**Screenshots**
![bug-secondaryitem2](https://user-images.githubusercontent.com/12270774/61355203-26ac2780-a874-11e9-84e2-45041f5ed154.JPG)

**Version of Corporate-ui**
- E.g 4.0.0-alpha.3

**Framework and version**
- Framework: Angular
- Version: 8

**Desktop:**
 - Browser: Chrome

**Smartphone:**
 - Device: all devices

**Comment by helloimela** [comment]
Good finding!
We are investigating this, probably need to remove overflow hidden from c-navigation.

**Comment by helloimela** [comment]
Styling fixes can be found here https://github.com/scania/scania-theme/pull/5
