### ISSUE TITLE
Feature - Show header link items on mobile view

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui-dev#168]
**Is your feature request related to a problem? Please describe.**
On mobile view, the link items in header is not displayed, we should have it on mobile view as well.

**Describe the solution you'd like**
Add header link items either before the main navigation links or after the main navigation links

![image](https://user-images.githubusercontent.com/1199101/61518362-9d2e5e00-aa09-11e9-92d0-5207edbb7b7f.png)

* We don't have it in the current solution and we don't have a final design

**Comment by mxuwku** [comment]
Here a proposal how to display header links in mobile.
https://xd.adobe.com/spec/5804c5eb-ad82-4e3b-6b89-5957c3ca6a5e-2e35/

**Comment by helloimela** [comment]
[Link to preview](https://d1kybmg72qo0dt.cloudfront.net/build/global/branch/feature/header_link_items_mobile/www/index.html?selectedKind=Templates&selectedStory=Header%20Showcase&full=0&addons=0&stories=1&panelRight=0)

**Comment by mmexvr** [comment]
#176

**Comment by helloimela** [comment]
Merged to master #179 #174
