### ISSUE TITLE
Structure of SRC folder...

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui-dev#17]
One question: in the src folder there is a folder "components" that contains only custom elements. Is there a chance that we further on want to divide components into custom-elements and something else? In the UX Library, today there are these kind of components: Custom Elements, HTML Components and JavaScript components. Shouldn't they all be in the same repository if we would like to auto generate documentation, code samples and StoryBook stories?

It feels wise to start out with a sub level for "custom-elements" where we store the <c(ustom)-header> and <c(ustom)-footer> etc etc?

:-)

/J

**Comment by awinny** [comment]
Maybe, haven´t thought about those types of "components" yet. Although the src folder is kinda ment for "code" related things, but one might argue that a design prototype also might be a component.

**Comment by scania-bootstrap** [comment]
Pull request: Sample structure for component types #20  (can be rejected when discussed).

**Comment by scania-bootstrap** [comment]
Here are our current (kind of):         h-nav-pills          component:

<ul class="nav nav-pills">
  <li class="active"><a href="#">Home</a></li>
  <li><a href="#">Profile</a></li>
  <li><a href="#">Messages</a></li>
</ul>

Just not sure how this is going to be stored and autogenerated to the Design System Documentation (currently the UX Library.

**Comment by scania-bootstrap** [comment]
Compare to the same issue for BlazeUI:

Component is available as a Custom Element:
https://www.blazeui.com/objects/drawers

Component is only available using HTML & CSS:
https://www.blazeui.com/objects/medias

**Comment by scania-bootstrap** [comment]
The difference between between a h-navigation and and a c-navigation is only that one of them is wrapped into a custom element. They are both components but one of them is easier to use (and harder to modify).

**Comment by scania-bootstrap** [comment]
From a UX point of view, there is no what so ever, difference between components (design patterns) so we really need to be able to, in the documentation, list custom elements mixed with html components as well as JavaScript components.

**Comment by scania-bootstrap** [comment]
Really advanced JavaScript components for example, like the Tabulator, make no sense to turn into a custom elements because it adds nothing of value? Basically, the only thing it would add is a custom elements wrapper around a often quite advanced call. I think that in the long run will create maintainance for us, that adds no or little value to the end developer.

**Comment by helloimela** [comment]
So here we have 3 types of Components based on the technology :
- HTML Components : adding classes to standard HTML elements
- Javascript Components: standard HTML elements with classes and behavior added from bootstrap native or any other plugin
- Custom Element: our own generated custom elements that might use the HTML Components classes inside.

From the code-relative perspective, there are only 2 types of components: **standard HTML** (with only css classes or javascript behavior) & **custom element**.

So here maybe we don't need a specific folder named as the component types (such as html-components or js-components).
For example in this folder:
`src/components/html-components/h-button-dropdown/`
there will be styles in this folder that is used in three of all component types. Is this the `global` folder that we have in our current setup? Maybe yes. If we want to keep this structure (separating HTML elements & custom elements in the code) we could do something like:
```bash
├── src
│   ├── components //custom elements
│   ├── html 
│   │   ├── scss  // styles 
│   │   ├── demo // demo page for all HTML & JS components
...
```

**Comment by awinny** [comment]
Dont like it tbh.
We can discuss it further on.

**Comment by mmexvr** [comment]
Stale, 
Closed for now

Reopen if necessary
