### ISSUE TITLE
Bug - Initial load is delayed using Angular 

### ISSUE THREAD

**Issue by edo-polimac-scania** [scania/corporate-ui-dev#184]
**Describe the bug**
We are experiencing small delay with creating and styling corporate ui web components in Angular application. This is issue occurs on every refresh page and sometimes happens that they stay unstyled. Obvious example is with header components. Live example is visible on  [official example with Angular](https://scania.github.io/corporate-ui-angular/)

We are using:
- Angular 8
- npm i corporate-ui-dev --save for including Corporate UI in project
- Rest of implementation is from your documentation

**To Reproduce**
1. Go to  [official example with Angular](https://scania.github.io/corporate-ui-angular/)
2. Refresh page several times
3. Notice how navbar has small delay in styling

**Expected behavior**
Page to be styled when loading first time.

**Screenshots**
NA

**Version of Corporate-ui**
- E.g 4.0.0-alpha.3

**Framework and version**
If you use any specific framework please provide information
- Framework: Angular
- Version: 8

**Application link**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Chrome 
 - Version Version 71.0.3578.80

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by helloimela** [comment]
Fixed and merged in #251
