### ISSUE TITLE
Add correct modal examples in storybook

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui-dev#192]
**Describe the interaction pattern**<br/>
Right now modal shows all the bootstrap example

**Describe the improvement**<br/>
A clear and concise description of what kind of improvement you have in mind.
Should show correct examples that are done in scania-theme

**If applicable, please provide steps to reproduce**<br/>
1. Go to localhost and storybook

**Comment by helloimela** [comment]
Fixed in #198
