### ISSUE TITLE
Active class for link items in c-footer 

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui-dev#209]
**Describe the interaction pattern**<br/>
There is no active styles for `a` element in the `c-footer`.

**Describe the improvement**<br/>
We should add consistent styling for `active` class and attribute for link items in the c-footer.

**If applicable, please provide steps to reproduce**<br/>
1. Go to https://d1kybmg72qo0dt.cloudfront.net/build/global/branch/master/www/index.html?selectedKind=Elements&selectedStory=c-footer&full=0&addons=0&stories=1&panelRight=0
2. Scroll down to c-footer with link items
3. F12 & inspect link element, add attribute class active or active attribute to true
4. See styling

**Screenshots**<br/>
How it looks in Vue example:
![image](https://user-images.githubusercontent.com/1199101/66297294-b3083c80-e8ef-11e9-8193-c782ab4f0e1e.png)

How it looks in Storybook:
![image](https://user-images.githubusercontent.com/1199101/66297352-cddab100-e8ef-11e9-9c5d-b1377699993c.png)

**Comment by mmexvr** [comment]
scania/scania-theme#71
