### ISSUE TITLE
Feature - Investigate upgrades to the interface setup

### ISSUE THREAD

**Issue by awinny** [scania/corporate-ui-dev#211]
**Is your feature request related to a problem? Please describe.**
Our current interface is used manly for developers. Maybe we could use "UX-Library" as a part of the local setup.

**Describe the solution you'd like**
We would need to create a UX-Library that uses some kind of headless CMS that can be used both in the local as well as on the live version of UX-Library.

**Describe alternatives you've considered**
Remove storybook in favour of a pure stencil one. This would speed up the development interface. There is a running branch with this that can be found here: [Simplify and refactor local server](https://github.com/scania/corporate-ui-dev/tree/feature/Simplify_and_refactor_local_server)

**Additional context**
This would remove the currently pretty complex storybook setup that we have with a more simple one.

**Comment by mmexvr** [comment]
Close this, split up in jira and github

- CMS part in jira
- Remove of storybook added in github
- Stencil upgrade added in github
