### ISSUE TITLE
Feature - labelling components with beta or stable in storybook

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui-dev#53]
Problems:
Right now we hide elements from storybook that are not neccesary at this time around and might cause rendering issue. But all these elements are available in the source code. So it might be strange for developers if they see these components in source code but we can't find it in storybook.
See: `filteredComponents` variable in  `.storybook/kinds/components.js`

**Describe the solution**
Display all components that are available in the source code so we can test it. Add filter labels such as 'beta' or 'stable'

**Comment by helloimela** [comment]
A nice example of component status: https://www.carbondesignsystem.com/components/component-status

**Comment by mmexvr** [comment]
Exprimental components has been removed, might be something into the feature
