### ISSUE TITLE
Feature - Hello World Component

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui-dev#54]
As long as there is not very much documentation available for new developers, one would look for the simpliest possbible component to start out at. 

Wouldn't a c-hello-world custom elements be a natural place to start?

**Comment by scania-bootstrap** [comment]
A simple as ever possible.

**Comment by mmexvr** [comment]
Create a pull-request, check it out if it is something we want.

Added a new category also called start

#57

**Comment by mmexvr** [comment]
Having something similare in the documentation might be a good idea? https://stenciljs.com/docs/my-first-component
