### ISSUE TITLE
File, folder listing on our static server

### ISSUE THREAD

**Issue by awinny** [scania/corporate-ui-dev#55]
**Describe the interaction pattern**<br/>
When we used cdn77 as our host provider, it was possible to list files and folders when accessing:
https://static.scania.com/{vendors,build}/
This is no longer possible when we are using aws as our static provider.

**Describe the improvement**<br/>
Add listing configuration certain folders, to make it possible to find hosted resources.

**Comment by mmexvr** [comment]
For some backgrund,

AWS s3 doesn't support listing of "folders" on AWS.

Right now if you go to static.scania.com, if we didn't have a redirect, it would just how a XML file with everything we have in our bucket.
