### ISSUE TITLE
Improvement - Storybook template section should render an html file in iframe

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui-dev#61]
**Describe the interaction pattern**<br/>
Right now, template  is rendered by requiring the html file and grab all the content inside a c-container

**Describe the improvement**<br/>
We should have a way to contain the template in a more isolated way for example using iframe, so it can be re-used as a single html file, (to really serve its purpose as a template).

**Comment by helloimela** [comment]
We want to have the example shows the whole html code so it is easy for user to use the example page.
For example, in codepen, you can have something like this (we have html tag along with head & meta tags): 

![image](https://user-images.githubusercontent.com/1199101/63325387-47134a00-c32a-11e9-92f7-d7502984708d.png)

In our setup, we only render content, so user only see something like this: 

![image](https://user-images.githubusercontent.com/1199101/63325436-67db9f80-c32a-11e9-9cd3-d15764a733d5.png)

**Comment by mmexvr** [comment]
For now the current solution works, we are evaluating alternatives to storybook
