### ISSUE TITLE
Feature - NPM Create a release flow

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui-dev#63]
**Is your feature request related to a problem? Please describe.**
We should have a way to have a build folder containing all the stuff we want to publish in npm.

**Describe the solution you'd like**
Build only important files to build folder then publish in npm.
Things we should have in the build folder could be:
- helpers.js (to import components as module)
- separated components modules generate by stencil
- core corporate-ui.js generated by stencil (?)
- storybook pages
- themes generated in css format
- something more ?

**Comment by mmexvr** [comment]
Initial part of this is done
