### ISSUE TITLE
Improvements for the Corporate Footer

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui-dev#64]
- The footer needs the Social Media Component for displaying icons.
- Both header and footer (all components?) should support opening links in similar way that the HTML standard supports, for example target="_blank" and with the download attribute as well as other standard HTML items.
- Add size attribute or similar to make the footer tiny (same as Fleet Positioning), medium (same as app) or large (public). Should that be size="medium" etc or what?

Current documentation for the Footer: https://scania.github.io/corporate-ui-docs/developer/bootstrap-original-docs.html#corporate-footer

**Comment by mmexvr** [comment]
#70 Related

**Comment by mmexvr** [comment]
#65 Related

**Comment by helloimela** [comment]
- Social media component has been added #82 
- Dynamic attributes has been added #78

**Comment by helloimela** [comment]
#95
