### ISSUE TITLE
Improvement - Add target blank option for header and main-navigation items

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui-dev#70]
**Describe the interaction pattern**<br/>
Right now we don't have the option of target: _blank for opening a new window from the links inside header and main-navigation

**Describe the improvement**<br/>
Possible option for target _blank on links inside header and main-navigation

**Additional context**<br/>
Maybe other components should have this option.

**Comment by awinny** [comment]
Notice, that we might wanna have a way to automatically set attributes dynamically to the link.
Meening, we might change location to href and simply let the component add whatever the user choses.

**Comment by helloimela** [comment]
Fixed in #78
