### ISSUE TITLE
Browser support information & polyfill needed

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui-dev#89]
**Is your feature request related to a problem? Please describe.**
Test browser support for the following components :
- Header
- Footer
- Social media
- Navigation
- Content
- Theme

**Comment by helloimela** [comment]
## Browser test

❌ components not rendered
🔴 rendered with styling error
✔️ rendered and worked as expected

Component | Chrome | Firefox | IE11 | Edge
 --- | --- | --- | --- | --- 
Header | :heavy_check_mark: | :heavy_check_mark: | :red_circle: | :red_circle:
Footer | :heavy_check_mark: | :heavy_check_mark: | :red_circle: | :red_circle:
Social media | :heavy_check_mark: | :heavy_check_mark: | :red_circle: | :red_circle:
Navigation | :heavy_check_mark: | :heavy_check_mark: | :red_circle: | :red_circle:
Content | :heavy_check_mark: | :heavy_check_mark: | :red_circle: | :red_circle:
Theme | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:

##  IE11 specific bugs
 
Bug | Workarounds
 --- | --- 
Host styling is not working | IE shadow DOM polyfill, other way could be: stencil generated a common class for IE browser, sc-c-header-h, can be used to fix styling  
c-code-sample rendered two times creating two examples |
The use of flexbox messed up in IE | Common issues & workarounds : [link](https://github.com/philipwalton/flexbugs)
Slot styling (::slotted) | https://github.com/webcomponents/webcomponentsjs
CSS Variables | https://github.com/jhildenbiddle/css-vars-ponyfill

**Comment by mmexvr** [comment]
Looks good! @helloimela 

Safari should be added also, something we can look into.

We should have a seperate list for supporting frameworks, like angular and react. or just include it the same list as a seperate column

**Comment by mmexvr** [comment]
Note:
Maybe add a seperate project for browser support

**Comment by mmexvr** [comment]
https://github.com/scania/corporate-ui-dev/wiki
